# Generate HTML for all categories
# This script generates the HTML for the category.html page

def generate_category_html(name, video_count):
    """Generate HTML for a single category card"""
    # Simple icon mapping based on common category keywords
    icon_mapping = {
        "3D": "fas fa-cube",
        "4K": "fas fa-video",
        "69": "fas fa-bed",
        "Amateur": "fas fa-user",
        "Anal": "fas fa-backward",
        "Anime": "fas fa-dragon",
        "Arab": "fas fa-globe-africa",
        "Asian": "fas fa-globe-asia",
        "Ass": "fas fa-moon",
        "Babe": "fas fa-heart",
        "BBC": "fas fa-mars",
        "BBW": "fas fa-circle",
        "BDSM": "fas fa-handcuffs",
        "Big Ass": "fas fa-moon",
        "Big Cock": "fas fa-mars",
        "Big Tits": "fas fa-venus",
        "Blonde": "fas fa-user",
        "Blowjob": "fas fa-kiss",
        "Bondage": "fas fa-handcuffs",
        "Boobs": "fas fa-venus",
        "Brazilian": "fas fa-globe-americas",
        "Bukkake": "fas fa-shower",
        "Cartoon": "fas fa-paint-brush",
        "Cheating": "fas fa-user-secret",
        "Chinese": "fas fa-globe-asia",
        "Chubby": "fas fa-circle",
        "Classic": "fas fa-clock",
        "College": "fas fa-graduation-cap",
        "Comic": "fas fa-book",
        "Compilation": "fas fa-list",
        "Cosplay": "fas fa-mask",
        "Creampie": "fas fa-seedling",
        "Cum": "fas fa-tint",
        "Cumshot": "fas fa-tint",
        "Cunnilingus": "fas fa-kiss",
        "Cute": "fas fa-heart",
        "Czech": "fas fa-globe-europe",
        "Deepthroat": "fas fa-kiss",
        "Desi": "fas fa-globe-asia",
        "Doctor": "fas fa-user-md",
        "Doggystyle": "fas fa-dog",
        "Double Penetration": "fas fa-arrows-alt-h",
        "Ebony": "fas fa-user",
        "Exotic": "fas fa-globe",
        "Facial": "fas fa-smile",
        "Fantasy": "fas fa-hat-wizard",
        "Feet": "fas fa-footprints",
        "Femdom": "fas fa-venus",
        "Fingering": "fas fa-hand-point-up",
        "First Time": "fas fa-star",
        "Fisting": "fas fa-hand-rock",
        "Fitness": "fas fa-dumbbell",
        "Footjob": "fas fa-footprints",
        "French": "fas fa-globe-europe",
        "Funny": "fas fa-laugh",
        "Gangbang": "fas fa-users",
        "Gay": "fas fa-mars-double",
        "German": "fas fa-globe-europe",
        "GILF": "fas fa-venus",
        "Girlfriend": "fas fa-heart",
        "Glasses": "fas fa-glasses",
        "Gloryhole": "fas fa-circle",
        "Goth": "fas fa-moon",
        "Grandpa": "fas fa-mars",
        "Granny": "fas fa-venus",
        "Group Sex": "fas fa-users",
        "Hairy": "fas fa-leaf",
        "Handjob": "fas fa-hand-paper",
        "Hardcore": "fas fa-fire",
        "HD": "fas fa-video",
        "Hentai": "fas fa-dragon",
        "Horny": "fas fa-fire",
        "Hospital": "fas fa-hospital",
        "Hot": "fas fa-fire",
        "Indian": "fas fa-globe-asia",
        "Interracial": "fas fa-globe",
        "Italian": "fas fa-globe-europe",
        "Japanese": "fas fa-globe-asia",
        "JAV": "fas fa-video",
        "Kissing": "fas fa-kiss",
        "Korean": "fas fa-globe-asia",
        "Latex": "fas fa-paint-roller",
        "Latina": "fas fa-globe-americas",
        "Lesbian": "fas fa-venus-double",
        "Lingerie": "fas fa-tshirt",
        "Machine": "fas fa-cogs",
        "Maid": "fas fa-broom",
        "Massage": "fas fa-spa",
        "Masturbating": "fas fa-hand-paper",
        "Mature": "fas fa-venus",
        "Medical": "fas fa-user-md",
        "Mexican": "fas fa-globe-americas",
        "MILF": "fas fa-venus",
        "Mom": "fas fa-venus",
        "Monster": "fas fa-paw",
        "Nurse": "fas fa-user-md",
        "Office": "fas fa-briefcase",
        "Old": "fas fa-venus",
        "Orgasm": "fas fa-bolt",
        "Outdoor": "fas fa-tree",
        "Pakistani": "fas fa-globe-asia",
        "Parody": "fas fa-copy",
        "Party": "fas fa-glass-cheers",
        "POV": "fas fa-eye",
        "Pregnant": "fas fa-baby",
        "Public": "fas fa-users",
        "Pussy": "fas fa-venus",
        "Russian": "fas fa-globe-europe",
        "School": "fas fa-school",
        "Secretary": "fas fa-briefcase",
        "Seduce": "fas fa-heart",
        "Shaved": "fas fa-cut",
        "Shower": "fas fa-shower",
        "Skinny": "fas fa-arrows-alt-h",
        "Slave": "fas fa-chain",
        "Sleep": "fas fa-bed",
        "Small Tits": "fas fa-venus",
        "Solo": "fas fa-user",
        "Spanish": "fas fa-globe-europe",
        "Squirt": "fas fa-tint",
        "Stockings": "fas fa-socks",
        "Story": "fas fa-book",
        "Strap-On": "fas fa-plug",
        "Stripper": "fas fa-gem",
        "Student": "fas fa-graduation-cap",
        "Swallow": "fas fa-kiss",
        "Swinger": "fas fa-users",
        "Teacher": "fas fa-chalkboard-teacher",
        "Teen": "fas fa-child",
        "Threesome": "fas fa-users",
        "Toys": "fas fa-plug",
        "Uniform": "fas fa-tshirt",
        "Vintage": "fas fa-clock",
        "Virgin": "fas fa-star",
        "Webcam": "fas fa-camera",
        "Wife": "fas fa-heart",
        "Yoga": "fas fa-spa",
        "Young": "fas fa-child"
    }
    
    # Find the best matching icon
    icon_class = "fas fa-tag"  # default icon
    name_lower = name.lower()
    for key, icon in icon_mapping.items():
        if key.lower() in name_lower:
            icon_class = icon
            break
    
    # Generate the HTML
    html = f'''                <div class="category-card">
                    <div class="category-icon">
                        <i class="{icon_class}"></i>
                    </div>
                    <h3>{name}</h3>
                    <span>{video_count} videos</span>
                </div>'''
    return html

# Sample categories for testing
categories = [
    ("18 Year Old", "32.1K"),
    ("3D", "669K"),
    ("3D Animation", "349K"),
    ("4K", "94.4K"),
    ("69", "7.73K"),
    ("Amateur", "269K"),
    ("Amateur Anal", "74.9K"),
    ("Amateur Blowjob", "105K"),
    ("Anal", "223K"),
    ("Anal Compilation", "22.6K"),
    ("Anime", "845K"),
    ("Asian", "210K"),
    ("Asian Blowjob", "84K"),
    ("Ass", "446K"),
    ("Babe", "165K"),
    ("BBC (Big Black Cock)", "44.3K"),
    ("BBW", "43.2K"),
    ("BDSM", "130K"),
    ("Big Ass", "252K"),
    ("Big Cock", "283K"),
    ("Big Tits", "449K"),
    ("Blonde", "138K"),
    ("Blowjob", "341K"),
    ("Bondage", "42K"),
    ("Boobs", "623K"),
    ("Brazilian", "9.18K"),
    ("Bukkake", "19.1K"),
    ("Cartoon", "358K"),
    ("Cheating", "40.6K"),
    ("Chinese", "14.7K"),
    ("Chubby", "17.3K"),
    ("Classic", "9.2K"),
    ("Compilation", "62.9K"),
    ("Cosplay", "67.8K"),
    ("Creampie", "240K"),
    ("Cum", "440K"),
    ("Cunnilingus", "49.7K"),
    ("Cute", "77.6K"),
    ("Czech", "7.91K"),
    ("Deepthroat", "98K"),
    ("Desi", "34.1K"),
    ("Doctor", "7.53K"),
    ("Doggystyle", "153K"),
    ("Double Penetration", "28.6K"),
    ("Ebony", "76.8K"),
    ("Exotic", "7.55K"),
    ("Facial", "102K"),
    ("Fantasy", "80.4K"),
    ("Feet", "29K"),
    ("Femdom", "29.8K"),
    ("Fingering", "78.2K"),
    ("First Time", "15.9K"),
    ("Fisting", "11.2K"),
    ("Footjob", "16.7K"),
    ("French", "12.3K"),
    ("Funny", "52K"),
    ("Gangbang", "37.3K"),
    ("German", "8.42K"),
    ("GILF", "1.93K"),
    ("Girlfriend", "31.5K"),
    ("Glasses", "10.1K"),
    ("Gloryhole", "4.54K"),
    ("Goth", "3.81K"),
    ("Grandpa", "6.15K"),
    ("Granny", "3.12K"),
    ("Group Sex", "43.5K"),
    ("Hairy", "19.9K"),
    ("Handjob", "42.1K"),
    ("Hardcore", "210K"),
    ("HD", "398K"),
    ("Hentai", "671K"),
    ("Horny", "89.2K"),
    ("Hospital", "2.96K"),
    ("Hot Milf", "203K"),
    ("Hot Mom", "203K"),
    ("Indian", "51.2K"),
    ("Interracial", "51K"),
    ("Italian", "6.32K"),
    ("Japanese", "147K"),
    ("JAV", "22.5K"),
    ("Kissing", "33.9K"),
    ("Korean", "3.93K"),
    ("Latex", "4.98K"),
    ("Latina", "56.7K"),
    ("Lesbian", "56.4K"),
    ("Lingerie", "79.9K"),
    ("Machine", "12.4K"),
    ("Maid", "11.6K"),
    ("Massage", "23.8K"),
    ("Masturbating", "126K"),
    ("Mature", "92.6K"),
    ("Medical", "18.9K"),
    ("Mexican", "8.32K"),
    ("MILF", "203K"),
    ("Mom", "223K"),
    ("Monster", "12.1K"),
    ("Nurse", "10.7K"),
    ("Office", "15.2K"),
    ("Old & Young", "34K"),
    ("Older", "42.3K"),
    ("Orgasm", "310K"),
    ("Outdoor", "148K"),
    ("Pakistani", "1.06K"),
    ("Parody", "25.7K"),
    ("Party", "15.6K"),
    ("POV", "180K"),
    ("Pregnant", "5.63K"),
    ("Public", "35.8K"),
    ("Pussy", "120K"),
    ("Russian", "10.8K"),
    ("School", "32.4K"),
    ("Secretary", "4.87K"),
    ("Seduce", "20.2K"),
    ("Shaved", "55.6K"),
    ("Shower", "12K"),
    ("Skinny", "24K"),
    ("Slave", "15.6K"),
    ("Sleep", "8.21K"),
    ("Small Tits", "71.4K"),
    ("Solo", "59.4K"),
    ("Spanish", "18.7K"),
    ("Squirt", "63.4K"),
    ("Stockings", "41.7K"),
    ("Story", "72.1K"),
    ("Strap-On", "6.48K"),
    ("Stripper", "3.12K"),
    ("Student", "30K"),
    ("Swallow", "19K"),
    ("Swinger", "12.4K"),
    ("Teacher", "15.6K"),
    ("Teen", "272K"),
    ("Teen Anal", "62.6K"),
    ("Threesome", "74.7K"),
    ("Toys", "116K"),
    ("Uniform", "15.3K"),
    ("Vintage", "6.32K"),
    ("Virgin", "9.12K"),
    ("Webcam", "8.56K"),
    ("Wife", "87.1K"),
    ("Young", "284K")
]

def main():
    # Generate HTML for all categories
    html_output = ""
    for category in categories:
        if len(category) == 2:
            name, count = category
            html_output += generate_category_html(name, count) + "\n"
        elif len(category) == 3:
            # Handle special cases like ("A", "Accidental Creampie", "192")
            # prefix, name, count = category
            name = category[1]
            count = category[2]
            html_output += generate_category_html(name, count) + "\n"
    
    # Save to a file
    with open("categories_output.html", "w", encoding="utf-8") as f:
        f.write(html_output)
    
    print(f"Generated HTML for {len(categories)} categories")
    print("Output saved to categories_output.html")

if __name__ == "__main__":
    main()