import os

# Categories data - name and video count
categories = [
    ("18 Year Old", "32.1K"),
    ("3D", "669K"),
    ("3D Animation", "349K"),
    ("3d Hentai", "267K"),
    ("4K", "94.4K"),
    ("69", "7.73K"),
    ("A", "Accidental Creampie", "192"),
    ("Adorable", "77.6K"),
    ("Adorable Anal", "17.2K"),
    ("Adorable Japanese", "17.6K"),
    ("Adultery", "40.6K"),
    ("Affair", "5.71K"),
    ("African Casting", "106"),
    ("African Cum In Mouth", "344"),
    ("Agent", "1.28K"),
    ("AI Generated", "12.6K"),
    ("Alluring", "2.14K"),
    ("Amateur", "269K"),
    ("Amateur Anal", "74.9K"),
    ("Amateur Blowjob", "105K"),
    ("Amateur Casting", "2.8K"),
    ("Amateur Creampie", "68.8K"),
    ("Amateur Cuckold", "8.52K"),
    ("Amateur Cum In Mouth", "18.3K"),
    ("Amateur DP", "10.6K"),
    ("Amateur Foursome", "858"),
    ("Amateur Homemade", "93.2K"),
    ("Amateur Lesbian", "18.9K"),
    ("Amateur POV", "44.8K"),
    ("Amateur Teen Anal 18+", "24.3K"),
    ("Amateur Threesome", "19.3K"),
    ("Amateur Wife Anal", "18.8K"),
    ("AMWF", "74"),
    ("Anal", "223K"),
    ("Anal Compilation", "22.6K"),
    ("Anal Creampie", "10.3K"),
    ("Anal Dildo", "1.3K"),
    ("Anal DP", "2.99K"),
    ("Anal Extreme", "16K"),
    ("Anal First Time", "7.17K"),
    ("Anal Fisting", "2.69K"),
    ("Anal Fuck", "42.2K"),
    ("Anal Gangbang", "14.1K"),
    ("Anal Hardcore", "56.1K"),
    ("Anal Mom", "63.3K"),
    ("Anal Orgasm", "94.5K"),
    ("Anal Orgy", "15.4K"),
    ("Anal Squirt", "27.5K"),
    ("Anal Surprise", "1.2K"),
    ("Anal Teen 18+", "62.6K"),
    ("Anal Threesome", "25.6K"),
    ("Anal Toying", "5.82K"),
    ("Animation", "932K"),
    ("Animation 3D", "349K"),
    ("Anime", "845K"),
    ("Anime Hentai", "671K"),
    ("Anime Uncensored", "154K"),
    ("Arab", "2.7K"),
    ("Arab Anal Sex", "907"),
    ("Arab Big Ass", "1.02K"),
    ("Arab Creampie", "509"),
    ("Arab Homemade", "303"),
    ("Arab Mom", "961"),
    ("Arab Money", "43"),
    ("Arab Pornstar", "182"),
    ("Arab Teen 18+", "546"),
    ("Argentinian", "3.05K"),
    ("Armpit", "1.22K"),
    ("Asian", "210K"),
    ("Asian & BBC (Big Black Cock)", "10.3K"),
    ("Asian & Indian", "6.99K"),
    ("Asian Ass", "84.4K"),
    ("Asian BDSM", "29.7K"),
    ("Asian Blowjob", "84K"),
    ("Asian Cheating", "11K"),
    ("Asian Cuckold", "4.21K"),
    ("Asian Extreme", "5.97K"),
    ("Asian Femdom", "5.78K"),
    ("Asian Fisting", "2.48K"),
    ("Asian Gangbang", "7.39K"),
    ("Asian Granny", "831"),
    ("Asian Hardcore", "43K"),
    ("Asian Homemade", "30.5K"),
    ("Asian Hotel", "2.56K"),
    ("Asian Lesbian", "10.2K"),
    ("Asian Massage Parlor", "205"),
    ("Asian Mature", "27.6K"),
    ("Asian MILF", "8.57K"),
    ("Asian POV", "35K"),
    ("Asian Squirt", "16.1K"),
    ("Asian Teen 18+", "63.4K"),
    ("Asian Teen Anal Sex 18+", "16.2K"),
    ("ASMR", "12.7K"),
    ("Ass", "446K"),
    ("Ass Worship", "5.34K"),
    ("Ass-To-Mouth", "6.48K"),
    ("Assfingering", "3.78K"),
    ("Assfucking", "42.2K"),
    ("Assjob", "941"),
    ("Athletic", "2.4K"),
    ("Audition", "6.3K"),
    ("B", "Babe", "165K"),
    ("Babysitter", "2.26K"),
    ("Bachelorette Party", "820"),
    ("Backstage", "598"),
    ("Balcony", "526"),
    ("Ball Busting", "1.05K"),
    ("Ballet", "197"),
    ("Balls", "21.3K"),
    ("Bar", "3.61K"),
    ("Barebacking", "4.7K"),
    ("Baseball Bat", "27"),
    ("BBC (Big Black Cock)", "44.3K"),
    ("BBC Anal", "17.2K"),
    ("BBC Compilation", "2.82K"),
    ("BBC DP", "3.55K"),
    ("BBC Gangbang", "3.84K"),
    ("BBC Latina", "4.28K"),
    ("BBC Orgasm", "17.1K"),
    ("BBC Wife", "11.4K"),
    ("BBW", "43.2K"),
    ("BBW Anal", "20.5K"),
    ("BBW Gangbang", "1.76K"),
    ("BBW MILF", "22.3K"),
    ("BBW Teen 18+", "197"),
    ("BBW Threesome", "3.76K"),
    ("BDSM", "130K"),
    ("BDSM Anal", "45.4K"),
    ("BDSM Extreme", "10.9K"),
    ("BDSM Gangbang", "8.86K"),
    ("BDSM Lesbian", "13.5K"),
    ("BDSM Slave", "9.9K"),
    ("BDSM Torture (BDSM)", "756"),
    ("Beach Stranger", "134"),
    ("Bear", "852"),
    ("Beauty", "165K"),
    ("Beauty Anal Sex", "34K"),
    ("Bedroom", "20K"),
    ("Behind The Scenes", "3.12K"),
    ("Berlin", "206"),
    ("Best Friend", "5.84K"),
    ("Big Ass", "252K"),
    ("Big Ass Anal", "85.4K"),
    ("Big Ass BBC", "20.7K"),
    ("Big Ass Blonde", "39.4K"),
    ("Big Ass Mature", "30.8K"),
    ("Big Ass Threesome", "19.2K"),
    ("Big Booty", "252K"),
    ("Big Cock", "283K"),
    ("Big Cock Anal Sex", "85.9K"),
    ("Big Natural Tits", "30.7K"),
    ("Big Nipples", "6.16K"),
    ("Big Tits", "449K"),
    ("Big Tits Anal", "112K"),
    ("Big Tits Asian", "96.6K"),
    ("Big Tits Ebony", "34.2K"),
    ("Big Tits Japanese", "62K"),
    ("Big Tits Mom", "131K"),
    ("Big Tits POV", "78.5K"),
    ("Big Tits Threesome", "36.4K"),
    ("Bikini", "7.81K"),
    ("Bikini Teen 18+", "2.23K"),
    ("Birthday", "1.87K"),
    ("Bisexual Encouragement", "72"),
    ("Bisexual Husband", "499"),
    ("Bisexual MMF", "153"),
    ("Black Beauty", "17.9K"),
    ("Black Butt", "3.76K"),
    ("Black Girl", "3.44K"),
    ("Black Lesbian", "5.22K"),
    ("Black Mom", "21.7K"),
    ("Blindfolded Surprise", "77"),
    ("Blond Teen 18+", "2.26K"),
    ("Blonde", "138K"),
    ("Blonde BBC", "7K"),
    ("Blonde Big Tits", "78.2K"),
    ("Blonde POV", "39.3K"),
    ("Blowjob", "341K"),
    ("Blowjob & Cumshot", "144K"),
    ("Blowjob Compilation", "24.6K"),
    ("Blowjob Swallow", "12.2K"),
    ("Boat", "1.32K"),
    ("Bodybuilder", "762"),
    ("Bondage", "42K"),
    ("Bondage Fuck", "20.9K"),
    ("Bondage Orgasm", "16.1K"),
    ("Boobs", "623K"),
    ("Boobs Sucking", "30.4K"),
    ("Boots", "5.5K"),
    ("Boss", "10.6K"),
    ("Boss Wife", "2.28K"),
    ("Bottle", "520"),
    ("Bound", "42K"),
    ("Boyfriend", "11.9K"),
    ("Brazilian", "9.18K"),
    ("Brazilian Amateur", "5.79K"),
    ("Brazilian Big Cock", "2.91K"),
    ("Brazilian Facial", "865"),
    ("Brazilian HD", "1.61K"),
    ("Brazilian Homemade", "1.54K"),
    ("Brazilian Hot Mom", "2.38K"),
    ("Brazilian Teen 18+", "2.87K"),
    ("Brazilian Wife", "1.24K"),
    ("Bride", "1.08K"),
    ("British Anal", "948"),
    ("Bubble Butt", "4.22K"),
    ("Bukkake", "19.1K"),
    ("Bulge", "1.06K"),
    ("Bus", "1.9K"),
    ("Busty MILF", "12.3K"),
    ("Busty Teen 18+", "4.02K"),
    ("Butt", "446K"),
    ("Buttfucking", "42.2K"),
    ("Buttplug", "2.57K"),
    ("BWC (Big White Cock)", "3.5K"),
    ("C", "Cage", "1.46K"),
    ("Cameltoe", "1.48K"),
    ("Caning", "284"),
    ("Cartoon", "358K"),
    ("Cartoon Mom", "89.4K"),
    ("Casting Amateur", "2.8K"),
    ("Caught", "10.5K"),
    ("Caught Cheating", "674"),
    ("Caught Masturbating", "1.3K"),
    ("CBT (Cock Ball Torture)", "1.45K"),
    ("CEI (Cum Eating Instructions)", "813"),
    ("CFNM", "2.77K"),
    ("Changing Room", "529"),
    ("Chastity", "1.19K"),
    ("Chastity Belt", "83"),
    ("Cheating", "40.6K"),
    ("Cheating Creampie", "10.4K"),
    ("Cheating Husband", "1.31K"),
    ("Cheating Mom", "252"),
    ("Cheerleader", "2.96K"),
    ("Chinese Amateur", "1.62K"),
    ("Chinese Babe", "929"),
    ("Chinese Cum", "2.26K"),
    ("Chinese Homemade", "698"),
    ("Chinese Teen 18+", "1.15K"),
    ("Chubby", "17.3K"),
    ("Chubby Creampie", "4.01K"),
    ("Chubby Teen 18+", "178"),
    ("Chubby Threesome", "890"),
    ("Classic", "9.2K"),
    ("Clit", "7.78K"),
    ("Close Up", "41.2K"),
    ("Close Up Pussy", "24.5K"),
    ("College Party", "1.4K"),
    ("Comic", "377K"),
    ("Competition", "1.16K"),
    ("Compilation", "62.9K"),
    ("Compilation Amateur", "11.5K"),
    ("Compilation Creampie", "17.7K"),
    ("Compilation Orgasm", "19.8K"),
    ("Condom", "2.33K"),
    ("Contortion", "94"),
    ("Cop", "2.71K"),
    ("Corset", "1.1K"),
    ("Cosplay", "67.8K"),
    ("Couch", "6.35K"),
    ("Cougar Anal", "4.11K"),
    ("Cougar BBC", "1.4K"),
    ("Cougar Creampie", "2.84K"),
    ("Country", "1.19K"),
    ("Couple Swap", "88"),
    ("Couple Threesome", "2.25K"),
    ("Crazy Japanese", "1.09K"),
    ("Creampie", "240K"),
    ("Creampie Compilation", "17.7K"),
    ("Creampie Gangbang", "12.8K"),
    ("Creampie MILF", "52.4K"),
    ("Creampie Mom", "55.9K"),
    ("Creampie Surprise", "1.27K"),
    ("Creampie Teen 18+", "88.4K"),
    ("Creamy Pussy", "4.92K"),
    ("Croatian", "22"),
    ("Cuckold", "24.1K"),
    ("Cuckold Gangbang", "1.21K"),
    ("Cuckold Humiliation", "2.44K"),
    ("Cuckquean", "429"),
    ("Cucumber", "579"),
    ("Cum", "440K"),
    ("Cum Covered", "5.66K"),
    ("Cum In Ass", "11.1K"),
    ("Cum In Mouth", "65.6K"),
    ("Cum In Mouth Compilation", "3.92K"),
    ("Cum In Pussy", "242K"),
    ("Cum Inside", "246K"),
    ("Cum Inside Compilation", "17.9K"),
    ("Cum Inside Pussy", "74K"),
    ("Cum On Tits", "7.12K"),
    ("Cum Slut", "39K"),
    ("Cum Swapping", "1.01K"),
    ("Cum Twice", "649"),
    ("Cumshot Compilation", "16.8K"),
    ("Cunnilingus", "49.7K"),
    ("Curvy Latina", "5.89K"),
    ("Curvy MILF", "14.7K"),
    ("Cute", "77.6K"),
    ("Cute Japanese", "17.6K"),
    ("Cute Korean", "314"),
    ("Cute Teen 18+", "2.54K"),
    ("Czech", "7.91K"),
    ("Czech Amateur", "708"),
    ("Czech Swingers", "42"),
    ("Czech Wife Swap", "3"),
    ("D", "Danish", "113"),
    ("Deepthroat", "98K"),
    ("Deepthroat BBC", "8.52K"),
    ("Deepthroat Compilation", "8.18K"),
    ("Deepthroat Cum", "59.6K"),
    ("Deepthroat Extreme", "8.32K"),
    ("Deepthroat Swallow", "6.63K"),
    ("Delivery Guy", "354"),
    ("Dentist", "66"),
    ("Desi Boobs", "12.5K"),
    ("Desi Hot Mom", "10K"),
    ("Desi MILF", "10K"),
    ("Desi Teen 18+", "9.08K"),
    ("Desperate", "2.11K"),
    ("Dick Flash", "65"),
    ("Dildo", "42K"),
    ("Dildo Riding", "4.9K"),
    ("Dinner", "1.42K"),
    ("Dirty Talk", "14.6K"),
    ("Doctor", "7.53K"),
    ("Doggystyle", "153K"),
    ("Doggystyle Compilation", "9.8K"),
    ("Doggystyle POV", "51.1K"),
    ("Doll", "7.3K"),
    ("Domination", "70.8K"),
    ("Dominatrix", "6.15K"),
    ("Double Penetration", "28.6K"),
    ("Double Pussy", "2.01K"),
    ("Downblouse", "848"),
    ("DP Compilation", "2.74K"),
    ("DP Teen 18+", "7.04K"),
    ("Dripping Wet Pussy", "4.78K"),
    ("Dungeon", "2.06K"),
    ("E", "Ebony", "76.8K"),
    ("Ebony Anal", "22.2K"),
    ("Ebony BWC", "971"),
    ("Ebony Interracial", "16.9K"),
    ("Ebony Lesbian", "5.22K"),
    ("Ebony MILF", "897"),
    ("Ebony Orgy", "4.56K"),
    ("Ebony Teen 18+", "395"),
    ("Edging", "8.08K"),
    ("Edging Handjob", "2.89K"),
    ("Electrified", "227"),
    ("English Subtitles", "5.13K"),
    ("European", "70.2K"),
    ("Exhibitionist Public", "941"),
    ("Exotic", "7.55K"),
    ("Expansion", "1.75K"),
    ("Extreme", "36.4K"),
    ("Extreme Gangbang", "1.91K"),
    ("Extreme Squirt", "4.93K"),
    ("F", "Face", "54.2K"),
    ("Face Fuck", "22K"),
    ("Face Sitting", "6.92K"),
    ("Facial Compilation", "4.18K"),
    ("Fake Tits", "3.5K"),
    ("Fantasy", "80.4K"),
    ("Fantasy Creampie", "15.3K"),
    ("Fat Cock", "32.1K"),
    ("Fat Pussy", "16.7K"),
    ("Feet", "29K"),
    ("Female Ejaculation", "63.4K"),
    ("Female Orgasm", "74.1K"),
    ("Female Orgasm Compilation", "6.8K"),
    ("Female POV", "1.67K"),
    ("Femboy 18+", "1.26K"),
    ("Femdom", "29.8K"),
    ("Femdom Handjob", "3.6K"),
    ("Femdom Humiliation", "3.28K"),
    ("Femdom Piss", "306"),
    ("Feminization", "278"),
    ("FFM", "5.56K"),
    ("FFM Anal", "1.3K"),
    ("Filipina Teen 18+", "359"),
    ("Fingering", "78.2K"),
    ("Fingering Pussy", "47.5K"),
    ("Finnish", "119"),
    ("First BBC", "1.38K"),
    ("First Time", "15.9K"),
    ("First Time Arab", "66"),
    ("First Time Indian", "748"),
    ("First Time Lesbian", "1.08K"),
    ("Fisting", "11.2K"),
    ("Fisting Gangbang", "665"),
    ("Fitness MILF", "2.42K"),
    ("Flirting", "1.13K"),
    ("Food", "5.28K"),
    ("Footjob", "16.7K"),
    ("Foreplay", "2.32K"),
    ("Foreskin", "38"),
    ("Forest", "4.73K"),
    ("Fraternity", "81"),
    ("Free Use", "309"),
    ("French Big Ass", "3.03K"),
    ("Friend", "27.3K"),
    ("FTM", "13"),
    ("Funny", "52K"),
    ("Fur", "642"),
    ("G", "Gagged (Bit or Ball)", "7.74K"),
    ("Gagging", "7.94K"),
    ("Game", "225K"),
    ("Gangbang", "37.3K"),
    ("Garden", "1.55K"),
    ("Garter Belts", "2.96K"),
    ("German BDSM", "11K"),
    ("German Femdom", "263"),
    ("Giantess", "3.24K"),
    ("GILF", "1.93K"),
    ("Girlfriend", "31.5K"),
    ("Girlfriends Mom", "7.84K"),
    ("Glass Dildo", "723"),
    ("Glasses", "10.1K"),
    ("Glasses Teen 18+", "2.36K"),
    ("Gloryhole", "4.54K"),
    ("Gloryhole Amateur", "481"),
    ("Gloryhole Anal", "685"),
    ("Gloryhole Compilation", "227"),
    ("Gloryhole Creampie", "600"),
    ("Gloryhole Swallow", "507"),
    ("Gorgeous", "17.2K"),
    ("Gorgeous Indian", "278"),
    ("Goth", "3.81K"),
    ("Goth Anal", "606"),
    ("Grandpa", "6.15K"),
    ("Grandpa & Teen 18+", "14"),
    ("Grandpa And Teen 18+", "1.66K"),
    ("Granny Interracial Sex", "457"),
    ("Greek", "251"),
    ("Group Sex", "43.5K"),
    ("Gynecologist", "517"),
    ("H", "Hair Pulling", "314"),
    ("Hairy", "19.9K"),
    ("Hairy Asian", "6.43K"),
    ("Hairy Japanese", "4.75K"),
    ("Hairy Lesbian", "1.77K"),
    ("Hairy Pussy", "9.81K"),
    ("Halloween", "3.12K"),
    ("Handcuffed", "345"),
    ("Happy Ending Massage", "2.13K"),
    ("Hard Fuck", "7.3K"),
    ("Hardcore Anal", "56.1K"),
    ("Hardcore Gangbang", "9.82K"),
    ("Hardcore Pornography", "190K"),
    ("HD", "398K"),
    ("Hentai", "671K"),
    ("Hentai Anal", "127K"),
    ("Hentai Bondage", "28.9K"),
    ("Hentai Mom", "125K"),
    ("Hentai Monster", "2.03K"),
    ("Hentai Uncensored", "150K"),
    ("High Heels Stockings", "7.54K"),
    ("Hippy", "136"),
    ("Hogtied", "704"),
    ("Homeless", "248"),
    ("Homemade", "93.2K"),
    ("Homemade Amateur", "93.2K"),
    ("Homemade Anal", "32.9K"),
    ("Homemade Creampie", "29.3K"),
    ("Homemade Latina", "13.4K"),
    ("Homemade Lesbian", "5.72K"),
    ("Homemade Teen 18+", "24K"),
    ("Homemade Threesome", "6.69K"),
    ("Horror", "3.3K"),
    ("Hospital", "2.96K"),
    ("Hot MILF", "203K"),
    ("Hot Mom", "203K"),
    ("Hot Mom Anal", "59.4K"),
    ("Hot Mom Anal Sex", "59.4K"),
    ("Hot Mom Creampie", "52.4K"),
    ("Hot Wife", "18K"),
    ("Huge Ass", "11.4K"),
    ("Huge Cock", "48.3K"),
    ("Huge Natural Tits", "582"),
    ("Humiliation", "12.6K"),
    ("Hunk", "559"),
    ("Husband Friend", "2.01K"),
    ("Husband Watches Wife", "700"),
    ("I", "In Indonesian", "1.79K"),
    ("In Japanese", "10.7K"),
    ("In Polish", "12"),
    ("In Russian", "728"),
    ("In Vietnamese", "703"),
    ("Indian Anal Sex", "7.74K"),
    ("Indian Ass", "11.4K"),
    ("Indian Babe", "3.38K"),
    ("Indian Boobs", "10.1K"),
    ("Indian Couple", "2.84K"),
    ("Indian Girlfriend", "207"),
    ("Indian Hot Mom", "7.92K"),
    ("Indian In Public", "1.12K"),
    ("Indian Lesbian", "1.68K"),
    ("Indian Mom", "10.9K"),
    ("Indian Reality", "181"),
    ("Indian Teen 18+", "7.18K"),
    ("Indian Threesome", "1.96K"),
    ("Indian Wife", "495"),
    ("Intense Orgasm", "16.9K"),
    ("Interracial", "51K"),
    ("Interracial Amateur", "18K"),
    ("Interracial Gangbang", "4.39K"),
    ("Italian Anal", "918"),
    ("Italian Classic", "115"),
    ("J", "Jail", "2.81K"),
    ("Jamaican", "619"),
    ("Japanese", "147K"),
    ("Japanese 69", "892"),
    ("Japanese Amateur", "54.3K"),
    ("Japanese Anal", "22K"),
    ("Japanese Anal Sex", "22K"),
    ("Japanese Ass", "46.6K"),
    ("Japanese Babe", "29.6K"),
    ("Japanese BDSM", "16.6K"),
    ("Japanese Beauty", "29.6K"),
    ("Japanese Big Cock", "21.7K"),
    ("Japanese Big Natural Tits", "5.36K"),
    ("Japanese Big Tits", "62K"),
    ("Japanese Bondage", "5.83K"),
    ("Japanese Bukkake", "4.02K"),
    ("Japanese Cheating", "5.17K"),
    ("Japanese Clit", "951"),
    ("Japanese Creampie", "51.3K"),
    ("Japanese Cum", "74K"),
    ("Japanese Doctor", "730"),
    ("Japanese English Subtitles", "1.45K"),
    ("Japanese Fetish", "18.2K"),
    ("Japanese Gangbang", "4.61K"),
    ("Japanese Grandpa", "616"),
    ("Japanese Granny", "327"),
    ("Japanese Group Sex", "6.64K"),
    ("Japanese Hard Fuck", "570"),
    ("Japanese Hardcore", "30.2K"),
    ("Japanese Homemade", "17.2K"),
    ("Japanese In Public", "5.11K"),
    ("Japanese Lesbian", "5.98K"),
    ("Japanese Massage", "5.66K"),
    ("Japanese Masturbation Solo", "2.54K"),
    ("Japanese Mature", "11.6K"),
    ("Japanese MILF", "21.8K"),
    ("Japanese Mom", "3.79K"),
    ("Japanese Neighbor", "464"),
    ("Japanese Oldy", "9.75K"),
    ("Japanese Orgasm", "46.7K"),
    ("Japanese Orgy", "6.64K"),
    ("Japanese Pantyhose", "1.62K"),
    ("Japanese Pornstar", "4.64K"),
    ("Japanese Slave", "1.95K"),
    ("Japanese Small Tits", "7.58K"),
    ("Japanese Story", "5.13K"),
    ("Japanese Teen 18+", "43.6K"),
    ("Japanese Teen Anal Sex 18+", "8.03K"),
    ("Japanese Wife", "2.12K"),
    ("JAV (Japanese Adult Video)", "22.5K"),
    ("Jerking Off", "13.8K"),
    ("Job Interview", "279"),
    ("Jock", "604"),
    ("JOI (Jerk Off Instructions)", "14K"),
    ("Juggs", "27.5K"),
    ("K", "Kissing", "33.9K"),
    ("Korean", "3.93K"),
    ("L", "Lactating", "1.65K"),
    ("Lady", "17.4K"),
    ("Landlord", "573"),
    ("Latex", "4.98K"),
    ("Latex Femdom", "974"),
    ("Latina", "56.7K"),
    ("Latina Amateur", "39.9K"),
    ("Latina BBC", "4.28K"),
    ("Latina Big Ass", "21.2K"),
    ("Latina Lesbian", "8.65K"),
    ("Latina Maid", "543"),
    ("Latina Mature", "5.4K"),
    ("Latina Mom", "13.1K"),
    ("Latina POV", "9.31K"),
    ("Latina Teen 18+", "415"),
    ("Latina Threesome", "5.68K"),
    ("Leather", "2.34K"),
    ("Lesbian", "56.4K"),
    ("Lesbian Amateur", "18.9K"),
    ("Lesbian Anal", "15.5K"),
    ("Lesbian Anal Fisting", "433"),
    ("Lesbian Ass Licking", "2.17K"),
    ("Lesbian BBW", "2.67K"),
    ("Lesbian BDSM", "13.5K"),
    ("Lesbian Bondage", "2.99K"),
    ("Lesbian First Time", "1.08K"),
    ("Lesbian Fisting", "2.15K"),
    ("Lesbian Gangbang", "2.09K"),
    ("Lesbian Granny", "1.05K"),
    ("Lesbian Hentai", "25.5K"),
    ("Lesbian Japanese", "5.98K"),
    ("Lesbian Kissing", "8.66K"),
    ("Lesbian Massage", "2.94K"),
    ("Lesbian Mature", "6.63K"),
    ("Lesbian Orgasm", "20.3K"),
    ("Lesbian Orgy", "3.5K"),
    ("Lesbian Rimming", "2.17K"),
    ("Lesbian Seduce", "1.22K"),
    ("Lesbian Seduction", "1.22K"),
    ("Lesbian Slave", "955"),
    ("Lesbian Strap On", "4.24K"),
    ("Les
```

# Generate HTML for ALL categories
# This script generates the HTML for the category.html page with all categories provided by the user

def generate_category_html(name, video_count):
    """Generate HTML for a single category card"""
    # Simple icon mapping based on common category keywords
    icon_mapping = {
        "3D": "fas fa-cube",
        "4K": "fas fa-video",
        "69": "fas fa-bed",
        "18": "fas fa-birthday-cake",
        "Amateur": "fas fa-user",
        "Anal": "fas fa-backward",
        "Anime": "fas fa-dragon",
        "Arab": "fas fa-globe-africa",
        "Asian": "fas fa-globe-asia",
        "Ass": "fas fa-moon",
        "Babe": "fas fa-heart",
        "BBC": "fas fa-mars",
        "BBW": "fas fa-circle",
        "BDSM": "fas fa-handcuffs",
        "Big Ass": "fas fa-moon",
        "Big Cock": "fas fa-mars",
        "Big Tits": "fas fa-venus",
        "Blonde": "fas fa-user",
        "Blowjob": "fas fa-kiss",
        "Bondage": "fas fa-handcuffs",
        "Boobs": "fas fa-venus",
        "Brazilian": "fas fa-globe-americas",
        "Bukkake": "fas fa-shower",
        "Cartoon": "fas fa-paint-brush",
        "Casting": "fas fa-audition",
        "Cheating": "fas fa-user-secret",
        "Chinese": "fas fa-globe-asia",
        "Chubby": "fas fa-circle",
        "Classic": "fas fa-clock",
        "College": "fas fa-graduation-cap",
        "Comic": "fas fa-book",
        "Compilation": "fas fa-list",
        "Cosplay": "fas fa-mask",
        "Creampie": "fas fa-seedling",
        "Cum": "fas fa-tint",
        "Cumshot": "fas fa-tint",
        "Cunnilingus": "fas fa-kiss",
        "Cute": "fas fa-heart",
        "Czech": "fas fa-globe-europe",
        "Deepthroat": "fas fa-kiss",
        "Desi": "fas fa-globe-asia",
        "Doctor": "fas fa-user-md",
        "Doggystyle": "fas fa-dog",
        "Double Penetration": "fas fa-arrows-alt-h",
        "DP": "fas fa-arrows-alt-h",
        "Ebony": "fas fa-user",
        "Exotic": "fas fa-globe",
        "Facial": "fas fa-smile",
        "Fantasy": "fas fa-hat-wizard",
        "Feet": "fas fa-footprints",
        "Femdom": "fas fa-venus",
        "Fingering": "fas fa-hand-point-up",
        "First Time": "fas fa-star",
        "Fisting": "fas fa-hand-rock",
        "Fitness": "fas fa-dumbbell",
        "Footjob": "fas fa-footprints",
        "French": "fas fa-globe-europe",
        "Funny": "fas fa-laugh",
        "Gangbang": "fas fa-users",
        "Gay": "fas fa-mars-double",
        "German": "fas fa-globe-europe",
        "GILF": "fas fa-venus",
        "Girlfriend": "fas fa-heart",
        "Glasses": "fas fa-glasses",
        "Gloryhole": "fas fa-circle",
        "Goth": "fas fa-moon",
        "Grandpa": "fas fa-mars",
        "Granny": "fas fa-venus",
        "Group Sex": "fas fa-users",
        "Hairy": "fas fa-leaf",
        "Handjob": "fas fa-hand-paper",
        "Hardcore": "fas fa-fire",
        "HD": "fas fa-video",
        "Hentai": "fas fa-dragon",
        "Horny": "fas fa-fire",
        "Hospital": "fas fa-hospital",
        "Hot": "fas fa-fire",
        "Indian": "fas fa-globe-asia",
        "Interracial": "fas fa-globe",
        "Italian": "fas fa-globe-europe",
        "Japanese": "fas fa-globe-asia",
        "JAV": "fas fa-video",
        "Kissing": "fas fa-kiss",
        "Korean": "fas fa-globe-asia",
        "Latex": "fas fa-paint-roller",
        "Latina": "fas fa-globe-americas",
        "Lesbian": "fas fa-venus-double",
        "Lingerie": "fas fa-tshirt",
        "Machine": "fas fa-cogs",
        "Maid": "fas fa-broom",
        "Massage": "fas fa-spa",
        "Masturbating": "fas fa-hand-paper",
        "Mature": "fas fa-venus",
        "Medical": "fas fa-user-md",
        "Mexican": "fas fa-globe-americas",
        "MILF": "fas fa-venus",
        "Mom": "fas fa-venus",
        "Monster": "fas fa-paw",
        "Nurse": "fas fa-user-md",
        "Office": "fas fa-briefcase",
        "Old": "fas fa-venus",
        "Orgasm": "fas fa-bolt",
        "Outdoor": "fas fa-tree",
        "Pakistani": "fas fa-globe-asia",
        "Parody": "fas fa-copy",
        "Party": "fas fa-glass-cheers",
        "POV": "fas fa-eye",
        "Pregnant": "fas fa-baby",
        "Public": "fas fa-users",
        "Pussy": "fas fa-venus",
        "Russian": "fas fa-globe-europe",
        "School": "fas fa-school",
        ("Secretary", "fas fa-briefcase"),
        "Seduce": "fas fa-heart",
        "Shaved": "fas fa-cut",
        "Shower": "fas fa-shower",
        "Skinny": "fas fa-arrows-alt-h",
        "Slave": "fas fa-chain",
        "Sleep": "fas fa-bed",
        "Small Tits": "fas fa-venus",
        "Solo": "fas fa-user",
        "Spanish": "fas fa-globe-europe",
        "Squirt": "fas fa-tint",
        "Stockings": "fas fa-socks",
        "Story": "fas fa-book",
        "Strap-On": "fas fa-plug",
        "Stripper": "fas fa-gem",
        "Student": "fas fa-graduation-cap",
        "Swallow": "fas fa-kiss",
        "Swinger": "fas fa-users",
        "Teacher": "fas fa-chalkboard-teacher",
        "Teen": "fas fa-child",
        "Threesome": "fas fa-users",
        "Toys": "fas fa-plug",
        "Uniform": "fas fa-tshirt",
        "Vintage": "fas fa-clock",
        "Virgin": "fas fa-star",
        "Webcam": "fas fa-camera",
        "Wife": "fas fa-heart",
        "Yoga": "fas fa-spa",
        "Young": "fas fa-child"
    }
    
    # Find the best matching icon
    icon_class = "fas fa-tag"  # default icon
    name_lower = name.lower()
    for key, icon in icon_mapping.items():
        if key.lower() in name_lower:
            icon_class = icon
            break
    
    # Generate the HTML
    html = f'''                <div class="category-card">
                    <div class="category-icon">
                        <i class="{icon_class}"></i>
                    </div>
                    <h3>{name}</h3>
                    <span>{video_count} videos</span>
                </div>'''
    return html

def read_categories_from_file():
    """Read categories from the text file"""
    categories = []
    with open("categories.txt", "r", encoding="utf-8") as f:
        lines = [line.strip() for line in f.readlines() if line.strip()]
        for i in range(0, len(lines), 2):
            if i + 1 < len(lines):
                name = lines[i]
                count = lines[i + 1]
                categories.append((name, count))
    return categories

def main():
    # Read categories from file
    categories = read_categories_from_file()
    
    # Generate HTML for all categories
    html_output = ""
    for name, video_count in categories:
        html_output += generate_category_html(name, video_count) + "\n"
    
    # Write to output file
    with open("generated_categories.html", "w", encoding="utf-8") as f:
        f.write(html_output)
    
    print(f"Generated HTML for {len(categories)} categories")

if __name__ == "__main__":
    main()
